### PR TITLE
Small error in docs

### PR DESCRIPTION
**Pull request by mzac**

### CODE REVIEW

**Comment by mzac** [comment]
Found this typo as I was updating the Home Assistant Aruba component to leverage your great library!  Good work!

https://github.com/home-assistant/core/pull/37187

**Comment by mww012** [comment]
Hey.  Thanks for checking it out!  That's actually why I originally wrote it!  Just haven't gotten to the point where I had created a component yet.  I'm actually a bit disappointed with the API that Aruba has built for this but it's better than nothing.  A lot of it returns the raw CLI output instead of structured data so I had to go the regex route for parsing.  Please let me know if you find any other issues.

I'll merge this in.

**Comment by mww012** [comment]
Sorry it took so long for me to respond.

**Comment by apaperclip** [comment]
I agree with your comments regarding the aruba api, maybe it's just a first iteration type of thing and a future version properly parameterize it (and maybe some versioning to boot). I too am using it for HA  which is how I found my issue that you merged in (thank you!)   Would you be interested in helping with the existing integration or can I encourage you to create a new one? The existing one needs some love (config flow) and other improvements that are out of my depth. I've been testing the changes @mzac has done but they wont merge in any yaml config changes so we're stuck.

**Pull request merged**
