### PR TITLE
Added support for parsing extended channels that contain E or S

### PR DESCRIPTION
**Pull request by apaperclip**
E|S support was removed with latest release.

### CODE REVIEW

**Comment by mww012** [comment]
Well crap.  I'm sorry man.  Still learning the ropes.  I'll merge this in and push it up to PyPI as 0.0.3

**Comment by mww012** [comment]
Done.  You should be able to pull it from PyPI now.

**Comment by apaperclip** [comment]
> Well crap. I'm sorry man. Still learning the ropes. I'll merge this in and push it up to PyPI as 0.0.3

oh no problem at all. I'm quite the novice at git/github and python. I'm trying to figure it out and help where I can.

HA will need an instantpy version bump too right or does it makes sense to wait until the new integration is further along?

**Comment by mww012** [comment]
Yeah.  It'll need a version bump.  I think I made some good progress on the HA component a little earlier this afternoon but got pulled into something else right after.  I'll double check things this evening and try to get a working update pushed tonight or tomorrow.  Will push the version bump change with that.

**Pull request merged**
